## Кросплатформне програмування Python

### Матронін Олександр

*Група: ІПЗ-230076*

**Варіант 9**

## Завдання 1.

$$z_1 =(\cos\alpha-\cos\beta)^2 -(\sin\alpha-\sin\beta)^2$$

$$z_2 =-4\sin^2\dfrac{\alpha-\beta}{2}\cdot\cos(\alpha+\beta)$$

In [3]:
import numpy as np

alpha = np.pi / 4
beta = np.pi / 6

z1 = (np.cos(alpha) - np.cos(beta))**2 - (np.sin(alpha) - np.sin(beta))**2
z2 = -4 * np.sin((alpha - beta) / 2)**2 * np.cos(alpha + beta)

print(f"alpha = π/4, beta = π/6")
print(f"z1 = {z1:.6f}")
print(f"z2 = {z2:.6f}")

alpha = π/4, beta = π/6
z1 = -0.017638
z2 = -0.017638


## Завдання 2.

$$\text{arctg}\, x = \sum_{n=0}^{\infty}\dfrac{(-1)^n x^{2n+1}}{2n+1}=x-\dfrac{x^3}{3} + \dfrac{x^5}{5} -\dfrac{x^7}{7}+\ldots \quad|x|\leq 1$$

In [7]:
import numpy as np

x = 0.5
precision = 10

result_math = np.arctan(x)

result_series = 0.0
n = 0
while True:
    term = ((-1)**n * x**(2*n + 1)) / (2*n + 1)
    result_series += term
    n += 1
    if round(result_math, precision) == round(result_series, precision):
        break

print(f"x = {x}")
print(f"Точність: {precision} знаків після коми")
print(f"Значення пораховане першим способом: {result_math:.{precision}f}")
print(f"Значення пораховане другим способом: {result_series:.{precision}f}")
print(f"Кількість підсумованих членів ряду: {n}")

x = 0.5
Точність: 10 знаків після коми
Значення пораховане першим способом: 0.4636476090
Значення пораховане другим способом: 0.4636476090
Кількість підсумованих членів ряду: 15


## Завдання 3.

Сусідами елемента $A_{ij}$ у матриці назвемо елементи $A_{kl}$ з $i-1 \leq k \leq i+1$, $j-1 \leq l \leq j+1$, $(k,l) \neq (i,j)$. Операція згладжування матриці дає нову матрицю того ж розміру, кожен елемент якої отримується як середнє арифметичне наявних сусідів відповідного елемента вихідної матриці.
1) Побудувати результат згладжування заданої матриці розмірності 10x10. Матрицю задати в коді програми. Генератор випадкових чисел не використовувати.
2) У згладженій матриці знайти суму модулів елементів, розташованих нижче головної діагоналі.

In [ ]:
import numpy as np

A = np.array([
    [ 3,  7, -2,  4,  1,  6, -5,  8,  2, -3],
    [ 1, -4,  5,  2, -7,  3,  9, -1,  6,  4],
    [-2,  8,  3, -6,  5,  1, -4,  7,  2, -5],
    [ 6, -1,  4,  9, -3,  2,  8, -6,  1,  3],
    [ 2,  5, -7,  1,  4, -8,  3,  5, -2,  7],
    [-3,  4,  6, -2,  7,  1, -9,  2,  8, -1],
    [ 5, -6,  2,  8, -1,  4,  3, -7,  6,  2],
    [ 1,  3, -5,  4,  6, -2,  7,  1, -4,  9],
    [-4,  2,  8, -3,  1,  5, -6,  3,  7, -2],
    [ 7, -1,  3,  6, -4,  8,  2, -5,  1,  4]
])

print("Вихідна матриця:")
print(A)

rows, cols = A.shape
B = np.zeros((rows, cols))

for i in range(rows):
    for j in range(cols):
        neighbors = []
        for k in range(i - 1, i + 2):
            for l in range(j - 1, j + 2):
                if (k, l) != (i, j) and 0 <= k < rows and 0 <= l < cols:
                    neighbors.append(A[k, l])
        B[i, j] = np.mean(neighbors)

print("\nЗгладжена матриця:")
print(np.round(B, 2))

total = 0
for i in range(rows):
    for j in range(cols):
        if i > j:
            total += abs(B[i, j])

print(f"\nСума модулів елементів нижче головної діагоналі: {total:.2f}")

Вихідна матриця:
[[ 3  7 -2  4  1  6 -5  8  2 -3]
 [ 1 -4  5  2 -7  3  9 -1  6  4]
 [-2  8  3 -6  5  1 -4  7  2 -5]
 [ 6 -1  4  9 -3  2  8 -6  1  3]
 [ 2  5 -7  1  4 -8  3  5 -2  7]
 [-3  4  6 -2  7  1 -9  2  8 -1]
 [ 5 -6  2  8 -1  4  3 -7  6  2]
 [ 1  3 -5  4  6 -2  7  1 -4  9]
 [-4  2  8 -3  1  5 -6  3  7 -2]
 [ 7 -1  3  6 -4  8  2 -5  1  4]]

Згладжена матриця:
[[ 1.33  0.6   2.8  -0.2   1.6   0.2   5.    2.2   2.8   4.  ]
 [ 2.4   2.88  1.5   0.38  2.    0.75  1.88  3.12  1.75  0.4 ]
 [ 2.    1.5   2.12  2.25  0.12  1.62  2.88  1.88  1.12  3.2 ]
 [ 2.4   2.38  1.5   0.12  1.    0.75  0.    2.5   1.38  0.6 ]
 [ 2.2   1.38  3.25  2.25  0.88  1.62 -0.62  0.62  2.38  1.8 ]
 [ 2.    0.5   0.62  2.5   0.88  0.38  0.38  0.88  1.5   4.2 ]
 [-0.2   1.62  1.5   2.12  3.25  1.5  -0.38  1.75  1.25  3.6 ]
 [ 0.    0.38  2.25  2.    2.    2.38  0.12  1.12  2.38  1.8 ]
 [ 2.4   1.5   1.12  2.38  2.5   1.5   2.38  0.38  0.88  3.4 ]
 [-1.    3.2   2.4   1.    3.4  -0.4   1.    1.4   1.4   2.  ]]

